name: MacBuild/release

on: 
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build executable
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}